version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: loan_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Maroon5maps$
      MYSQL_DATABASE: loan_risk_db
      MYSQL_USER: loan_user
      MYSQL_PASSWORD: loan_password
    ports:
      - "3307:3306"
    networks:
      - app-network

  fastapi:
    build: ./FastApiDocker/fastapi-loan-app
    container_name: fastapi-loan-container
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

  restapi:
    build: ./frontend-backend
    container_name: restapi-container
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://loan_mysql_container:3306/loan_risk_db
      SPRING_DATASOURCE_USERNAME: loan_user
      SPRING_DATASOURCE_PASSWORD: loan_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      FASTAPI_URL: http://fastapi-loan-container:8000/predict
    depends_on:
      mysql:
        condition: service_healthy
      fastapi:
        condition: service_started

networks:
  app-network:
    driver: bridge
