services:
  fastapi:
    build: ./fastapi        # Build from local folder
    container_name: fastapi-loan-container
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

  restapi:
    build: ./frontend-backend  # Build from local folder
    container_name: restapi-container
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://loan_mysql_container:3306/loan_risk_db
      SPRING_DATASOURCE_USERNAME: loan_user
      SPRING_DATASOURCE_PASSWORD: loan_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      FASTAPI_URL: http://fastapi-loan-container:8000/predict
    depends_on:
      mysql:
        condition: service_healthy
      fastapi:
        condition: service_started
